### PR TITLE
2022 05 maintenance

### PR DESCRIPTION
**Pull request by abachma2**
I made some changes beyond what was previously made in our hack-a-thon. I think it should address some of the issues with the nose to pytest conversion, but not all. We can see if @nsryan2 has made any advancements on those.

### CODE REVIEW

**Comment by gonuke** [comment]
I've reviewed these changes and incorporated these or similar fixes in my branch on cyclus/cyclus.  Note that I'm using a branch called `2023-maintenance-update` directly on `cyclus/cyclus` because it allows the docker images to be pushed to the GH container registry.

**Comment by gonuke** [comment]
@abachma2   I'm not going to merge this, since it's not into the branch that I'm still using and I have some different solutions to other things

**Comment by abachma2** [comment]
Thats fine. I just figured this was the best way to show the changes I had made beyond our co-working. Feel free to close this PR.

**Comment by gonuke** [comment]
Understood!  I just didn't want to close this without explanation

**Pull request closed without merging**
